server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # 不使用Eureka服务进行注册
    fetch-registry: false # 不要在本地缓存注册表信息
  server:
    wait-time-in-ms-when-sync-empty: 5  # 在服务器接收请求之前等待的初始时间
